### ISSUE TITLE
Why body class in corpComment ?

### ISSUE THREAD

**Issue by madhavanand-github** [ByteGrad/Professional-JavaScript-Course#1]
As we can have only 1 body tag, may I know the purpose of adding a class named “body” in body tag.

**Comment by ByteGrad** [comment]
I switch back and forth on this. Any way is fine, it doesn’t matter. It’s
purely your preference. I currently don’t add a class to body/html tags.

**Comment by madhavanand-github** [comment]
Thanks 👍

**Comment by madhavanand-github** [comment]
Thanks 👍
