### ISSUE TITLE
Doubt : Selection Property

### ISSUE THREAD

**Issue by madhavanand-github** [ByteGrad/Professional-JavaScript-Course#2]
**Project** : CorpComment

In heading we have used pseudo-class `selection` , which I tried playing around and understood, but I couldn't understand the use case of former one with `first-heading*::selection` 

I could see it's effect if I disable the property but couldn't really understand.

**Comment by ByteGrad** [comment]
The selector '.first-heading *::selection' will select all child elements in the first-heading (in this project, it's only the <span>-element).
