### ISSUE TITLE
What is use case of Backface Property ?

### ISSUE THREAD

**Issue by madhavanand-github** [ByteGrad/Professional-JavaScript-Course#3]
W3 School defines `backface-visibility` property as whether the back face of an element should be visible when facing the user.

I could see its effect, but I am unable to understand the use case and property itself.

**Comment by ByteGrad** [comment]
Sometimes with CSS animations & transitions there is a small 1-px 'glitch'. So with the introductory animation (when you load the page) some elements may shift by like 1px at the end. One 'trick' to try to prevent this is with 'backface-visibility: none', however this doesn't always work. The idea is that it puts the element in 3d-space and therefore gets more resources from the computer, which should prevent that 1px-shifting.
