### ISSUE TITLE
Fancy Counter CSS

### ISSUE THREAD

**Issue by imsaravanan** [ByteGrad/Professional-JavaScript-Course#5]
Media query at fancy counter CSS showing an error. Its says curly excepted in an "or" statement. I even copy and pasted your CSS code it still the same error. please check

**Comment by ByteGrad** [comment]
Hi, can you show me a screenshot?

**Comment by imsaravanan** [comment]
![Screen Shot 2023-12-01 at 8 20 43 AM](https://github.com/ByteGrad/Professional-JavaScript-Course/assets/33148404/b103c466-9142-4bb2-8deb-e03defba6268)

**Comment by imsaravanan** [comment]
Code and fancy counter app are working fine. Its just i am seeing that 1 error so I want clarify with you. Thanks for response. Appreciate it.
